### ISSUE TITLE
Chromedriver won't start unless I set `DISABLE_X11`

### ISSUE THREAD

**Issue by flaper87** [blueimp/chromedriver#5]
`chromedriver:latest` won't start for me unless I set `DISABLE_X11`, which then requires passing `--headless` to nightwatch.

Unfortunately, I don't see any logs or anything that would help me understand why this is happening. Any debugging hints?

**Comment by blueimp** [comment]
You likely need to set the `init: true` option in your chromedriver docker-compose config, which is required since I removed the `tini` binary from the image.
Please let me know if this helps.

P.S.:
I've deprecated the blueimp/nightwatch project in favor of [blueimp/wdio](https://github.com/blueimp/wdio).

**Comment by AndreKR** [comment]
This bit me when trying to run blueimp/chromedriver on Kubernetes. Maybe `DISABLE_X11=true` should be the default, otherwise docker-compose would be a hidden dependency?

**Comment by blueimp** [comment]
The `init` option is not `docker-compose` specific, but also available via plain `docker`:
https://docs.docker.com/engine/reference/run/#specify-an-init-process

With Kubernetes, there is also a way to provide an init system:
https://stackoverflow.com/a/51172104

That being said, it might make sense to reintroduce the `tini` binary and revert the following commit:
https://github.com/blueimp/basedriver/commit/efb114a0fc66d9dc1e16ac6ca26ae50b52eda327
